/*
 * Copyright (c) 2022 Huawei Device Co., Ltd.
 * Licensed under the Apache License,Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// thousandth
export const GOODS_LIST_HEIGHT: string = '20%';
export const GOODS_IMAGE_WIDTH: string = '40%';
export const GOODS_FONT_WIDTH: string = '60%';
export const GOODS_LIST_WIDTH: string = '94%';
export const LAYOUT_WIDTH_OR_HEIGHT: string = '100%';

// font-size
export const GOODS_LIST_PADDING: number = 8;
export const GOODS_EVALUATE_FONT_SIZE: number = 12;
export const NORMAL_FONT_SIZE: number = 16;
export const BIGGER_FONT_SIZE: number = 20;
export const MAX_FONT_SIZE: number = 32;

// margin
export const REFRESH_ICON_MARGIN_RIGHT: number = 20;
export const MARGIN_RIGHT: number = 32;

// width or height
export const ICON_WIDTH: number = 40;
export const ICON_HEIGHT: number = 40;

// list space
export const LIST_ITEM_SPACE: number = 16;

// navigation title
export const STORE: string = '商城';

// offset range
export const MAX_OFFSET_Y: number = 100;

// refresh time
export const REFRESH_TIME: number = 1500;

// Magnification
export const MAGNIFICATION: number = 2;
export const MAX_DATA_LENGTH: number = 12;

